#https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html
AWSTemplateFormatVersion: 2010-09-09
Description: ---

Parameters: 
  DBUser:
    NoEcho: true
    Description: The database admin account username
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: true
    Description: The database admin account password
    Type: String
    MinLength: 8
    MaxLength: 41
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  DBName:
    Default: ebdb
    Description: The database name
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
#Mappings: 
#sarebbero da mettere: instance 
#- DBInstanceClass
#- DBAllocatedStorage 
#- MultiAZDatabase
#cfr: https://s3.us-west-2.amazonaws.com/cloudformation-templates-us-west-2/RDS_MySQL_With_Read_Replica.template

Resources: 
  #in realtà però il security gruoup delle istanze con la porta 80 aperta sul LoadBalancer viene 
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open for web access
      # Lo usiamo come markup e basta
  DBEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open database for access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '3306'
        ToPort: '3306'
        SourceSecurityGroupName:
          Ref: WebServerSecurityGroup
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName:
        Ref: DBName
      Engine: MySQL
      #EngineVersion:
      #DBSubnetGroupName: QUESTO SOPRATTUTTO NON MI TORNA... NON DEVO SPECIFICARLO?!?! ALTRIMENTI USA IL DEFAULT!
      MultiAZ: false
      MasterUsername:
        Ref: DBUser
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      #StorageType: standard | gp2 | io1
      MasterUserPassword:
        Ref: DBPassword
      VPCSecurityGroups:
      - !GetAtt DBEC2SecurityGroup.GroupId
      #AvailabilityZone: 
      #BackupRetentionPeriod: 
      #DBInstanceIdentifier: 
      PubliclyAccessible: true
      Tags:
        - Key: keyname
          Value: value
  sampleApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: AWS Elastic Beanstalk Sample Application
  sampleApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        Ref: sampleApplication
      Description: AWS ElasticBeanstalk Sample Application Version
      SourceBundle:
        S3Bucket: !Sub "elasticbeanstalk-samples-${AWS::Region}"
        S3Key: php-newsample-app.zip
  sampleConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:
        Ref: sampleApplication
      Description: AWS ElasticBeanstalk Sample Configuration Template
      OptionSettings:
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '1'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '6'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        #Questo è il ruolo che viene dato alle istanze
        #Come policies ha queste 3: AWSElasticBeanstalkWebTier, AWSElasticBeanstalkMulticontainerDocker, AWSElasticBeanstalkWorkerTier
        Value: aws-elasticbeanstalk-ec2-role
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: SecurityGroups
        #Questo è un securitygroup che viene aggiunto alle istanze, oltre a quello che permette la comunicazione su porta 80 da Load Balancer, creato automaticamente
        Value: 
          Ref: WebServerSecurityGroup      
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: ServiceRole
        #The name of an IAM role that Elastic Beanstalk uses to manage resources for the environment.
        Value: aws-elasticbeanstalk-service-role
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: RDS_DB_NAME
        Value:
          Ref: DBName
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: RDS_HOSTNAME
        Value: !GetAtt DBInstance.Endpoint.Address
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: RDS_PORT
        Value: '3306'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: RDS_USERNAME
        Value:
          Ref: DBUser
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: RDS_PASSWORD
        Value:
          Ref: DBPassword
      SolutionStackName: 64bit Amazon Linux 2018.03 v2.9.12 running PHP 7.3
  sampleEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: sampleApplication
      Description: AWS ElasticBeanstalk Sample Environment
      TemplateName:
        Ref: sampleConfigurationTemplate
      VersionLabel:
        Ref: sampleApplicationVersion
#Outputs:


#Non funziona perchè devo associare il security group sulle macchine create da autoscaling group nel launch configuration...
#Vedere se questo può aiutare
#https://stackoverflow.com/questions/40671054/how-do-i-specify-a-security-group-for-elastic-beanstalk-launch-configuration-in

#C'è da creare anche VPC dedicata, con tutte le risorse che ne conseguono, con DB nella parte priivata e NAAT GAteway per le istanze...
#Next Steps:
#- Le istanze EC2 devono essere nella public o private subnets (se servite da Load balancer?)
#- Definire mappa per prendere parametri diversi tra PROD e DEV (es max autoscaling, dimensione del DB e repliche del DB)
#- Creare anche l'infrastruttura VPC (e tutte i componenti inerenti... Iternet Gateway, NAT Gateway, ....
#- According to best practices, separare queste definizioni.... ed organizzarle (rivedere come nei corsi)
#- Fare in modo che l'applicazione acceda ad S3 e quindi fare in modo di dargli ruolo che permetta questo (probabilmente il aws-elasticbeanstalk-ec2-role lo fa già, ma magari provare per test a dargli qualcosa di più restrittivo?)
#   quindi questo probabilmente implica definire il Rolo, la\e Policy e l'InstanceProfile (oppure verificare se si può direttamente associare il ruole)
#- Fare in  modo che le istanze EC2 siano accessibili via SSH (o direttamente o attraversio Bstion Host) prendendo come parametro di input del template la chiave KeyPair:KeyName
#- Provare ad usare Linux2 come piattaforma e vedere limitazioni, cose in più che bisogna fare
#- Valutare il meccanismo delle saved configurations, che è utile, perchè potrei configurare ambienti da console e poi
#   salvare la configurazione e estrarre le informazioni nel cloudformation
#   cfr: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environment-configuration-savedconfig.html
#- Cloudformation BP: use dedicated service role
#- Provare Cloudformation CLI e parameters files
#- Import cross-stack resources 
